# git-cliff ~ default configuration file
# https://git-cliff.org/docs/configuration
#
# Lines starting with "#" are comments.
# Configuration options are organized into tables and keys.
# See documentation for more information on available options.

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}## [{{ version
     | trim_start_matches(pat="synd-")
     | trim_start_matches(pat="api-")
     | trim_start_matches(pat="auth-")
     | trim_start_matches(pat="feed-")
     | trim_start_matches(pat="o11y-")
     | trim_start_matches(pat="stdx-")
     | trim_start_matches(pat="o11y-")
     | trim_start_matches(pat="term-")
    }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased] __release_date__
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }} by [@{{ commit.remote.username}}](https://github.com/{{ commit.remote.username }}) ([{{ commit.id | truncate(length=8, end="") }}](https://github.com/ymgyt/syndicationd/commit/{{ commit.id }}))
    {%- endfor %}
{% endfor %}
https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }}

{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution in #{{ contributor.pr_number }}
{% endfor %}

"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""
# postprocessors
postprocessors = [
  # { pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" }, # replace repository URL
]
[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
  # { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"}, # replace issue numbers
]
# regex for parsing and grouping commits
# comment like <!-- 0 --> for force order 
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->ğŸ“¡ Features" },
  { message = "^fix", group = "<!-- 1 -->ğŸ› Bug Fixes" },
  { message = "^doc", group = "ğŸ“š Documentation" },
  { message = "^docs", group = "ğŸ“š Documentation" },
  { message = "^perf", group = "ğŸƒ Performance" },
  { message = "^refactor", group = "ğŸ§¹ Refactor" },
  { message = "^chore(.*): [Aa]ppease clippy", group = "ğŸ§¹ Refactor"},
  { message = "^style", group = "ğŸ¨ Styling" },
  { message = "^test", group = "ğŸ”§ Testing" },
  { message = "^chore: [Rr]elease", skip = true },
  { message = "^chore: release.*", skip = true },
  { message = "^chore: changelog", skip = true },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "doc: fix typo", skip = true },
  { message = "^chore|ci", group = "âš™ï¸ Miscellaneous Tasks" },
  { body = ".*security", group = "ğŸ”’ Security" },
  { message = "^revert", group = "Revert" },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# regex for matching git tags
tag_pattern = "synd-.*-v[0-9].*"

# regex for skipping tags
skip_tags = "v0.1.0-beta.1"
# regex for ignoring tags
ignore_tags = ""
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# limit the number of commits included in the changelog.
# limit_commits = 42
